# _config.yml

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

#theme: minima
title: Bryan's Place


description: > 
  My blog. Particularly how to re-use old
  smartphones as a homelab using the
  Alpine linux system for mobile devices; PostmarketOS.

url: "https://bryansplace.github.io"
baseurl: "" 

minima:
  skin: 'auto' 
  
  nav_pages:
    - index.md
    - about.md
  show_excerpts: false

#hide_site_feed_link: true

header_pages:
  - index.md
  - about.md

plugins:
  - jekyll-toc             
#  - jekyll-feed           
#  - jekyll-seo-tag
#  - jekyll-archives


jekyll-toc: 
  title: "Contents"
  min_headers: 2
  max_headers: 2
  ordered_list: false


google_analytics: G-B1ECP5MEZE 
