# _config.yml

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

#theme: minima
title: Bryan's Place


description: > 
  My blog. 
  Stuff I want to document in case I have to do it again. Hopefully also useful to others.

url: "https://bryansplace.github.io"
baseurl: "" 

minima:
  skin: 'auto'
  nav_pages:
    - blog.md
    - projects.md
    - now.md
    - about.md
  show_excerpts: false


minima:
  skin: 'auto'
  nav_pages:
    - blog.md
    - projects.md
    - now.md
    - about.md
  show_excerpts: false


plugins:
  - jekyll-remote-theme
  - jekyll-toc                       
  - jekyll-seo-tag
#  - jekyll-archives


jekyll-toc: 
  title: "Contents"
  min_headers: 2
  max_headers: 2
  ordered_list: false


google_analytics: G-B1ECP5MEZE 
