theme: minima

title: Bryan's Place
description: >
  My blog. Particularly how to re-use old     
  smartphones as a homelab using the 
  Alpine linux system for mobile devices; PostmarketOS.

url: "https://bryansplace.github.io"
bsseurl: "" # subpath, eg /blog

minima:
  skin: 'solarized-light'

header_pages:
  - blog.md
  - about.md
  - contact.md



google_analytics: G-B1ECP5MEZE