# _config.yml

theme: minima
title: Bryan's Place


description: > 
  My blog. Particularly how to re-use old
  smartphones as a homelab using the
  Alpine linux system for mobile devices; PostmarketOS.

url: "https://bryansplace.github.io"
baseurl: "" 

minima:
  skin: 'solarized-light' 

header_pages:
  - blog.md                
  - Reuse_an_Old_Smart_Phone.md
  - about.md

plugins:
  - jekyll-toc             
#  - jekyll-feed           
#  - jekyll-seo-tag
#  - jekyll-archives


jekyll-toc: 
  title: "Contents"
  min_headers: 2
  max_headers: 3
  ordered_list: false


google_analytics: G-B1ECP5MEZE 
